[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  VITE_SOCKET_URL = "https://web-production-4161.up.railway.app"
  NPM_FLAGS = "--legacy-peer-deps"

[build.processing]
  skip_processing = false