[build]
  command = "npm run build:client"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  VITE_SOCKET_URL = "https://seu-app.railway.app"

[build.processing]
  skip_processing = false