[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
restartPolicy = "always"

[deploy.envs]
NODE_ENV = "production"

[[services]]
name = "web"
protocol = "http"
internal_port = 3001