[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300

[deploy.env]
NODE_ENV = "production"
PORT = "3001"
FRONTEND_URL = "https://dama-online.netlify.app"

[[services]]
name = "damas-online"
internal_port = "3001"

[services.http]
path = "/health"
interval = "30s"
timeout = "10s"

[services.limits]
memory = "512MB"
cpu = 0.5 