[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 180
healthcheckInterval = 30
restartPolicy = "on-failure"

[deploy.envs]
NODE_ENV = "production"

[[services]]
name = "web"
protocol = "http"
internal_port = 3001