[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicy = "on-failure"
numReplicas = 1

[deploy.envs]
PORT = "3001"
NODE_ENV = "production"

[[services]]
name = "web"
protocol = "http"
internal_port = 3001