[build]
builder = "nixpacks"
buildCommand = "npm install --omit=dev && npm run build:server"

[deploy]
startCommand = "node dist/server/index.js"
restartPolicy = "always"

[deploy.envs]
PORT = "3001"
FRONTEND_URL = "https://dama-online.netlify.app"
NODE_ENV = "production"