[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build:server"

[deploy]
startCommand = "npm start"
restartPolicy = "always"

[deploy.envs]
PORT = "3001"
FRONTEND_URL = "https://damaon.netlify.app"
NODE_ENV = "production"